import type {CoreHealthCheckResult, FindAndCountUsersResult, SortInput, FilterInput, User, Meta, FileInfo, FindAndCountTodosResult, Todo, CoreAuthModel, Auth, AuthSignInInput, AuthSignUpInput, UserCreateInput, UserInput, TodoCreateInput, TodoInput} from "./default"
import type { InputFields } from '#base-types/fields';

import { gqlQuery, gqlMutation, gqlSubscription } from '#imports';

import type { UseMutationReturn, UseSubscriptionReturn } from '@vue/apollo-composable';

import type { AsyncData } from 'nuxt/app';
export const useHealthCheckQuery = ( fields?: InputFields<CoreHealthCheckResult>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{healthCheck: CoreHealthCheckResult}, any>> => gqlQuery<{healthCheck: CoreHealthCheckResult}>('healthCheck', { fields, lazy, log})
export const useFindAndCountUsersQuery = (variables: { limit?: number, offset?: number, skip?: number, sort?: SortInput[], take?: number, filter?: FilterInput, samples?: number }, fields?: InputFields<FindAndCountUsersResult>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{findAndCountUsers: FindAndCountUsersResult}, any>> => gqlQuery<{findAndCountUsers: FindAndCountUsersResult}>('findAndCountUsers', {variables, fields, lazy, log})
export const useFindUsersQuery = (variables: { limit?: number, offset?: number, skip?: number, sort?: SortInput[], take?: number, filter?: FilterInput, samples?: number }, fields?: InputFields<User>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{findUsers: User[]}, any>> => gqlQuery<{findUsers: User[]}>('findUsers', {variables, fields, lazy, log})
export const useGetUserQuery = (variables: { id: string }, fields?: InputFields<User>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{getUser: User}, any>> => gqlQuery<{getUser: User}>('getUser', {variables, fields, lazy, log})
export const useGetVerifiedStateQuery = (variables: { token: string },  lazy?: boolean, log?: boolean): Promise<AsyncData<{getVerifiedState: boolean}, any>> => gqlQuery<{getVerifiedState: boolean}>('getVerifiedState', {variables, fields: null, lazy, log})
export const useRequestPasswordResetMailQuery = (variables: { email: string },  lazy?: boolean, log?: boolean): Promise<AsyncData<{requestPasswordResetMail: boolean}, any>> => gqlQuery<{requestPasswordResetMail: boolean}>('requestPasswordResetMail', {variables, fields: null, lazy, log})
export const useGetMetaQuery = ( fields?: InputFields<Meta>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{getMeta: Meta}, any>> => gqlQuery<{getMeta: Meta}>('getMeta', { fields, lazy, log})
export const useGetFileInfoQuery = (variables: { filename: string }, fields?: InputFields<FileInfo>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{getFileInfo: FileInfo}, any>> => gqlQuery<{getFileInfo: FileInfo}>('getFileInfo', {variables, fields, lazy, log})
export const useFindAndCountTodosQuery = (variables: { limit?: number, offset?: number, skip?: number, sort?: SortInput[], take?: number, filter?: FilterInput, samples?: number }, fields?: InputFields<FindAndCountTodosResult>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{findAndCountTodos: FindAndCountTodosResult}, any>> => gqlQuery<{findAndCountTodos: FindAndCountTodosResult}>('findAndCountTodos', {variables, fields, lazy, log})
export const useFindTodosQuery = (variables: { limit?: number, offset?: number, skip?: number, sort?: SortInput[], take?: number, filter?: FilterInput, samples?: number }, fields?: InputFields<Todo>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{findTodos: Todo[]}, any>> => gqlQuery<{findTodos: Todo[]}>('findTodos', {variables, fields, lazy, log})
export const useGetTodoQuery = (variables: { id: string }, fields?: InputFields<Todo>[] | null, lazy?: boolean, log?: boolean): Promise<AsyncData<{getTodo: Todo}, any>> => gqlQuery<{getTodo: Todo}>('getTodo', {variables, fields, lazy, log})
export const useLogoutMutation = (variables: { allDevices?: boolean },  log?: boolean): Promise<UseMutationReturn<{logout: boolean}, any>> => gqlMutation<{logout: boolean}>('logout', {variables, fields: null, log})
export const useRefreshTokenMutation = ( fields?: InputFields<CoreAuthModel>[] | null, log?: boolean): Promise<UseMutationReturn<{refreshToken: CoreAuthModel}, any>> => gqlMutation<{refreshToken: CoreAuthModel}>('refreshToken', { fields, log})
export const useSignInMutation = (variables: { input: AuthSignInInput }, fields?: InputFields<Auth>[] | null, log?: boolean): Promise<UseMutationReturn<{signIn: Auth}, any>> => gqlMutation<{signIn: Auth}>('signIn', {variables, fields, log})
export const useSignUpMutation = (variables: { input: AuthSignUpInput }, fields?: InputFields<Auth>[] | null, log?: boolean): Promise<UseMutationReturn<{signUp: Auth}, any>> => gqlMutation<{signUp: Auth}>('signUp', {variables, fields, log})
export const useCreateUserMutation = (variables: { input: UserCreateInput }, fields?: InputFields<User>[] | null, log?: boolean): Promise<UseMutationReturn<{createUser: User}, any>> => gqlMutation<{createUser: User}>('createUser', {variables, fields, log})
export const useDeleteUserMutation = (variables: { id: string }, fields?: InputFields<User>[] | null, log?: boolean): Promise<UseMutationReturn<{deleteUser: User}, any>> => gqlMutation<{deleteUser: User}>('deleteUser', {variables, fields, log})
export const useResetPasswordMutation = (variables: { token: string, password: string },  log?: boolean): Promise<UseMutationReturn<{resetPassword: boolean}, any>> => gqlMutation<{resetPassword: boolean}>('resetPassword', {variables, fields: null, log})
export const useUpdateUserMutation = (variables: { input: UserInput, id: string }, fields?: InputFields<User>[] | null, log?: boolean): Promise<UseMutationReturn<{updateUser: User}, any>> => gqlMutation<{updateUser: User}>('updateUser', {variables, fields, log})
export const useVerifyUserMutation = (variables: { token: string },  log?: boolean): Promise<UseMutationReturn<{verifyUser: boolean}, any>> => gqlMutation<{verifyUser: boolean}>('verifyUser', {variables, fields: null, log})
export const useDeleteFileMutation = (variables: { filename: string }, fields?: InputFields<FileInfo>[] | null, log?: boolean): Promise<UseMutationReturn<{deleteFile: FileInfo}, any>> => gqlMutation<{deleteFile: FileInfo}>('deleteFile', {variables, fields, log})
export const useUploadFileMutation = (variables: { file: any }, fields?: InputFields<FileInfo>[] | null, log?: boolean): Promise<UseMutationReturn<{uploadFile: FileInfo}, any>> => gqlMutation<{uploadFile: FileInfo}>('uploadFile', {variables, fields, log})
export const useUploadFilesMutation = (variables: { files: any[] },  log?: boolean): Promise<UseMutationReturn<{uploadFiles: boolean}, any>> => gqlMutation<{uploadFiles: boolean}>('uploadFiles', {variables, fields: null, log})
export const useCreateTodoMutation = (variables: { input: TodoCreateInput }, fields?: InputFields<Todo>[] | null, log?: boolean): Promise<UseMutationReturn<{createTodo: Todo}, any>> => gqlMutation<{createTodo: Todo}>('createTodo', {variables, fields, log})
export const useDeleteTodoMutation = (variables: { id: string }, fields?: InputFields<Todo>[] | null, log?: boolean): Promise<UseMutationReturn<{deleteTodo: Todo}, any>> => gqlMutation<{deleteTodo: Todo}>('deleteTodo', {variables, fields, log})
export const useUpdateTodoMutation = (variables: { id: string, input: TodoInput }, fields?: InputFields<Todo>[] | null, log?: boolean): Promise<UseMutationReturn<{updateTodo: Todo}, any>> => gqlMutation<{updateTodo: Todo}>('updateTodo', {variables, fields, log})
export const useUserCreatedSubscription = ( fields?: InputFields<User>[] | null, log?: boolean): Promise<UseSubscriptionReturn<{userCreated: User}, any>> => gqlSubscription<{userCreated: User}>('userCreated', { fields, log})
export const useTodoCreatedSubscription = ( fields?: InputFields<Todo>[] | null, log?: boolean): Promise<UseSubscriptionReturn<{todoCreated: Todo}, any>> => gqlSubscription<{todoCreated: Todo}>('todoCreated', { fields, log})