name: Next release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies 📦️
        run: npm ci

      - name: Install dependencies
        run: cd playground/nuxt-app && npm ci && npm run build

      - run: npm run build

      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - run: npm version prerelease --preid=dev

      - name: Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push -o ci.skip

      - name: Publish 🚀
        shell: bash
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Deploy notification
        if: always()
        uses: adamkdean/simple-slack-notify@master
        with:
          channel: "#deployments"
          status: ${{ job.status }}
          success_text: "Version (#${{ steps.package-version.outputs.current-version}}) von @lenne.tech/nuxt-base wurde erfolgreich released."
          failure_text: "Release (#${{ steps.package-version.outputs.current-version}}) von @lenne.tech/nuxt-base ist fehlgeschlagen."
          cancelled_text: "Release (#$${{ steps.package-version.outputs.current-version}}) von @lenne.tech/nuxt-base wurde abgebrochen."
