name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - run: npx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Build playground
        run: cd playground/nuxt-app && pnpm install && pnpm build

      - name: Build
        run: pnpm build

      - uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Deploy notification
        if: always()
        uses: adamkdean/simple-slack-notify@master
        with:
          channel: "#deployments"
          status: ${{ job.status }}
          success_text: "Version (#${{github.ref_name}}) von @lenne.tech/nuxt-base wurde erfolgreich released."
          failure_text: "Release (#${{github.ref_name}}) von @lenne.tech/nuxt-base ist fehlgeschlagen."
          cancelled_text: "Release (#${{github.ref_name}}) von @lenne.tech/nuxt-base wurde abgebrochen."
